SELECT ID as name, DATEDIFF(MONTH, START_DATE, FINISH_DATE) AS duration_in_months
FROM project
WHERE DATEDIFF(MONTH, START_DATE, FINISH_DATE) = (
    SELECT MAX(DATEDIFF(MONTH, START_DATE, FINISH_DATE))
    FROM project
);
