CREATE TABLE IF NOT EXISTS worker (
   ID BIGSERIAL PRIMARY KEY,
   NAME VARCHAR(1000) CHECK (LENGTH(name ) >= 2 AND LENGTH(name ) <= 1000),
   BIRTHDAY DATE CHECK (YEAR(BIRTHDAY ) > 1900),
   LEVEL  ENUM('Trainee', 'Junior', 'Middle', 'Senior') NOT NULL,
   SALARY INT CHECK (Salary BETWEEN 100 AND 100000) NOT NULL
);
CREATE TABLE IF NOT EXISTS client (
   ID BIGSERIAL PRIMARY KEY,
   NAME VARCHAR(1000) CHECK (LENGTH(name ) >= 2 AND LENGTH(name ) <= 1000)
);
CREATE TABLE IF NOT EXISTS project  (
   ID BIGSERIAL PRIMARY KEY,
   CLIENT_ID BIGINT,
   START_DATE DATE,
   FINISH_DATE DATE
);
CREATE TABLE IF NOT EXISTS project_worker  (
   PROJECT_ID BIGINT,
   WORKER_ID BIGINT,
   PRIMARY KEY (PROJECT_ID, WORKER_ID)
);
