SELECT
    P.ID AS NAME,
    COALESCE(SUM(W.SALARY * DATEDIFF(MONTH, P.START_DATE, P.FINISH_DATE)), 0) AS PRICE
FROM
    PROJECT P
LEFT JOIN
    PROJECT_WORKER PW ON P.ID = PW.PROJECT_ID
LEFT JOIN
    WORKER W ON PW.WORKER_ID = W.ID
GROUP BY
    P.ID, P.CLIENT_ID, P.START_DATE, P.FINISH_DATE
ORDER BY
   PRICE DESC;